### ISSUE TITLE
Broken docker build/admin page

### ISSUE THREAD

**Issue by Fingel** [LCOGT/main_website#7]
We had an issue today where the admin site for the main website was inaccessible, throwing errors:

raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)

When building the image, pip throws the following warnings:

```
django-contrib-comments 1.9.0 has requirement Django>=1.11, but you'll have django 1.10.8 which is incompatible.
mezzanine 4.3.1 has requirement django<2.1,>=1.11, but you'll have django 1.10.8 which is incompatible.
django-reversion 3.0.2 has requirement django>=1.11, but you'll have django 1.10.8 which is incompatible.
```

It appears the requirements file doesn't lock the version of mezzanine:

https://github.com/LCOGT/main_website/blob/master/lco_global/requirements.pip#L4

This should probably be changed to install from PyPI, not master.

The container was restarted, and now the admin page is accessible (whitenoise errors are gone)

However, trying to edit a page results in the error:

`django.urls.exceptions.NoReverseMatch: Reverse for 'page' not found. 'page' is not a valid view function or pattern name.`

Upon further investigation, somehow Django 1.11 is installed in the currently deployed image, even though django is locked to 1.10 in this repo:

https://github.com/LCOGT/main_website/blob/master/lco_global/requirements.pip#L3

Unfortunately, building a docker image from the currently checked out source code results in an image that does not run, so it cannot be deployed. I'm not sure how the current image was built but it looks like the result of local modifications. The main website admin functionality is partially broken, but for fear of totally breaking the whole site, it will remain this way until this can be sorted out, as currently this source code results in a totally broken image.

**Comment by zemogle** [comment]
I fixed it about 30 mins ago. There was some crazy dependency war with installed packages which meant I need to upgrade to Dj 1.11. Whitenoise then messed up. Not sure how it all for fubar, but I fixed and deployed the container. Should all be working now.

**Comment by Fingel** [comment]
OK, can you commit whatever changes you made? The latest commit is from Aug 30 on this repo, so if anyone of us try to redeploy we'll be pushing a broken image.

**Comment by Fingel** [comment]
Still can't edit pages: https://lco.global/admin/pages/page/290/change/?parent=314

**Comment by talister** [comment]
Various links seem to be broken too e.g:

- https://lco.global/events/
- https://lco.global/observatory/capabilities
- https://lco.global/astronomers/opportunities

**Comment by jnation3406** [comment]
I've added back in some of the urls.py stuff that was removed and seems to be needed for mezzanine to function. The normal links should be working again. I can't set the admin page stuff because I don't have permissions.

**Comment by jnation3406** [comment]
I tested that admin page and it loaded as well, so I redeployed everything with our versioning scheme (mezzanine:latest). I guess everything is working now but we should still update libraries / switch mezzanine to use the pypi version instead of the latest commit.

**Comment by zemogle** [comment]
Thanks guys. Mezzanine's latest release has a bug (it doesn't resize PNGs) in it which is why I'm using the dev version (which is how we ended up in this pickle). I'm back in the office on Monday and I'll take a look at making it more robust.

**Comment by zemogle** [comment]
I had time to look at the `3.2.1` release of Mezzanine and this fixes the PNG and JPEG thumbnail issue (although its helpfully not in the release notes). I've updated the docker image to use the official release and deployed after extensive testing. Thanks again @jnation3406 and @Fingel for fixing my late night, panicked fudging last week.
